### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Gouthamve** [mjibson/mog#15]
Hi, I am new to GoLang but I wanted to build something very similar mog. 
I have decided to contribute to mog and I think it would be helpful to have documentation for me to get started.

Also a roadmap/checklist of what all have been achieved till date would be great.

And +1 for writing the music server.

Thanks,
Goutham

**Comment by mjibson** [comment]
The release notes for each version contain the major changes since the last. The website lists the current major features. What kind of documentation are you interested in? Are you looking for a list of open problems? Mostly it'd be this:

1. Use mog
1. Figure out something it doesn't do that you want it to do.
1. Do it.

Here's my current wishlist:

1. Google Music radio
1. Google Music and soundcloud playlists
1. Youtube (needs vorbis or AAC decoder)
1. Ogg Vorbis (I'm already working on this: https://github.com/mjibson/vorbis)
1. SPC (Super Nintendo) decoding (I'm also working on this: https://github.com/mjibson/spc/tree/gme)
1. Album and Artist list in the UI

Other useful features that I don't care about, but others may:
1. Spotify
1. AAC (iTunes, Apple music format)

**Comment by Gouthamve** [comment]
Okay. Sounds good. And forgive me if I sounded like an idiot, I am a complete newbie to go.
Also, I wanted some api docs actually. It would help me build a custom solution I wanted.

I was thinking of trying youtube integration. Happy to know you are working on it.

I think I would start working on the Album and Artist List first and then move on to gm and sound cloud playlists

Thanks,
Goutham
